[package]
name = "bevy_breakout_game_tutorial"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.7", features = ["dynamic"] }
iyes_loopless = "0.6.1"
rand = "0.8.5"
